# Generated by Django 5.2.1 on 2025-06-14 23:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number', regex='^01[0125][0-9]{8}$')], verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian Address in Arabic', regex='^[\\u0600-\\u06FF\\s\\d]+(?:\\s[\\u0600-\\u06FF\\s\\d]+)*$')], verbose_name='Address')),
                ('city', models.CharField(blank=True, choices=[('القاهرة', 'القاهرة'), ('الجيزة', 'الجيزة'), ('الاسماعيلية', 'الاسماعيلية'), ('الفيوم', 'الفيوم'), ('المنيا', 'المنيا'), ('المنوفية', 'المنوفية'), ('الوادي الجديد', 'الوادي الجديد'), ('القليوبية', 'القليوبية'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الدقهلية', 'الدقهلية'), ('الدمياط', 'الدمياط'), ('البحرالاحمر', 'البحرالاحمر')], max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, choices=[('مصر', 'مصر')], default='مصر', max_length=100, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian Postal Code', regex='^(?:[1-9]\\d{2}|[1-9]\\d{4})$')], verbose_name='Postal Code')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile picture (max 2MB)', null=True, upload_to='profile_pictures/%Y/%m/%d/', verbose_name='Profile Image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('activation_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activation Key')),
                ('activation_key_expires', models.DateTimeField(blank=True, null=True, verbose_name='Activation Key Expires')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-date_joined'],
            },
        ),
    ]
