# Generated by Django 5.1.1 on 2025-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='loved_by_users', to='product.product', verbose_name='Favorite Products'),
        ),
    ]
