# Generated by Django 5.2.1 on 2025-06-22 21:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='account_pro_city_7d4847_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='account_pro_date_jo_48c820_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
