# Generated by Django 5.1.1 on 2025-05-18 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian Address in Arabic', regex='^[\\u0600-\\u06FF\\s\\d]+(?:\\s[\\u0600-\\u06FF\\s\\d]+)*$')], verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('الجيزة', 'الجيزة'), ('القاهرة', 'القاهرة'), ('الاسماعيلية', 'الاسماعيلية'), ('الفيوم', 'الفيوم'), ('المنيا', 'المنيا'), ('المنوفية', 'المنوفية'), ('الوادي الجديد', 'الوادي الجديد'), ('القليوبية', 'القليوبية'), ('الشرقية', 'الشرقية'), ('الغربية', 'الغربية'), ('الدقهلية', 'الدقهلية'), ('الدمياط', 'الدمياط'), ('البحرالاحمر', 'البحرالاحمر')], max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('مصر', 'مصر')], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian Postal Code', regex='^(?:[1-9]\\d{2}|[1-9]\\d{4})$')], verbose_name='Postal Code'),
        ),
    ]
