# Generated by Django 5.2.1 on 2025-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='Is this product trending?', verbose_name='Trending'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('new', 'New'), ('hot', 'Hot'), ('sale', 'Sale')], default='new', max_length=40, verbose_name='Tag'),
        ),
    ]
