# Generated by Django 5.2.1 on 2025-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bg_color',
            field=models.CharField(blank=True, help_text="Background color for tag (e.g. #000 or 'blue')", max_length=20, null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text="Text color for tag (e.g. #fff or 'red')", max_length=20, null=True, verbose_name='Color'),
        ),
    ]
