# Generated by Django 5.1 on 2024-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDview',
            field=models.ManyToManyField(blank=True, related_name='users_see_it', to='accounts.profile', verbose_name='User see It'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDcart',
            field=models.ManyToManyField(blank=True, related_name='users_cart_it', to='accounts.profile', verbose_name='User cart It'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDlove',
            field=models.ManyToManyField(blank=True, related_name='users_love_it', to='accounts.profile', verbose_name='User Love It'),
        ),
    ]
