# Generated by Django 5.1 on 2024-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_prdtags_alter_category_catslug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overall_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATimage',
            field=models.ImageField(upload_to='category_pictures/', verbose_name='Category Image'),
        ),
    ]
