# Generated by Django 5.2.1 on 2025-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount percentage on the product', max_digits=5, null=True, verbose_name='Discount'),
        ),
    ]
