# Generated by Django 5.2.1 on 2025-06-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_bg_color_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='key',
        ),
    ]
