# Generated by Django 5.1 on 2024-09-21 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_prdview_alter_product_prdcart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REVcontent', models.TextField(max_length=1000, verbose_name='Product Review')),
                ('REVproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_review', to='product.product')),
                ('REVuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
