# Generated by Django 5.1.1 on 2025-04-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='Review'),
        ),
    ]
