# Generated by Django 5.1.1 on 2025-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cost'),
        ),
    ]
