# Generated by Django 5.1 on 2024-09-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_revcreated_at_review_revrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDcart',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PIMGproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='REVrating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
