# Generated by Django 5.1 on 2024-09-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_prdcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDlove',
        ),
    ]
