# Generated by Django 5.1.1 on 2025-04-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_confirmation_code_and_more'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_image',
            field=models.ImageField(default=-2000, upload_to=None, verbose_name='PayImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_phone',
            field=models.CharField(default=0.0005, max_length=11),
            preserve_default=False,
        ),
    ]
