# Generated by Django 5.2.1 on 2025-06-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vodafonecashpayment',
            options={'verbose_name': 'Vodafone Cash Payment', 'verbose_name_plural': 'Vodafone Cash Payments'},
        ),
        migrations.AddField(
            model_name='vodafonecashpayment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
