# Generated by Django 5.1 on 2024-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRFemail', models.EmailField(max_length=100, verbose_name='Email')),
                ('PRFdate_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Joined')),
                ('PRFslug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Profile Slug')),
                ('PRFfirst_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('PRFlast_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('PRFphone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('PRFaddress', models.TextField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('PRFcity', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('PRFcountry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('PRFpostal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('PRFprofile_image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Image')),
                ('PRFdate_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
