# Generated by Django 5.1 on 2024-10-05 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PRFcart',
            field=models.ManyToManyField(blank=True, related_name='users_cart_it', to='product.product', verbose_name='User cart It'),
        ),
        migrations.AddField(
            model_name='profile',
            name='PRFlove',
            field=models.ManyToManyField(blank=True, related_name='users_love_it', to='product.product', verbose_name='User Love It'),
        ),
        migrations.AddField(
            model_name='profile',
            name='PRFuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
