# Generated by Django 5.1 on 2024-09-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PRFcart',
            field=models.ManyToManyField(blank=True, related_name='users_cart_it', to='accounts.profile', verbose_name='User cart It'),
        ),
    ]
