# Generated by Django 5.1 on 2024-10-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='PRFcart',
        ),
    ]
