# Generated by Django 5.1 on 2024-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_prfcart'),
        ('product', '0006_remove_product_prdlove'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PRFlove',
            field=models.ManyToManyField(blank=True, related_name='users_love_it', to='product.product', verbose_name='User Love It'),
        ),
    ]
