# Generated by Django 5.1.1 on 2025-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_pictures/', verbose_name='Image')),
                ('desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Brand description')),
            ],
        ),
    ]
