# Generated by Django 5.1 on 2024-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDname', models.CharField(max_length=40)),
                ('BRDdesc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Brand description')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARname', models.CharField(max_length=40)),
                ('VARdesc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Variant description')),
            ],
        ),
    ]
