# Generated by Django 5.1.1 on 2025-04-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='BRDdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='BRDname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='VARdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='VARname',
            new_name='name',
        ),
    ]
