# Generated by Django 5.2.1 on 2025-05-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='image',
            new_name='logo',
        ),
    ]
