# Generated by Django 5.1.1 on 2025-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_brddesc_brand_desc_rename_brdname_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
