# Generated by Django 5.1.1 on 2025-04-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_brand_slug_variant_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
