# Generated by Django 5.1.1 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_pictures/', verbose_name='Image'),
        ),
    ]
