# Generated by Django 5.1 on 2024-10-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRTquantity', models.IntegerField(default=1)),
                ('CRTcreated_at', models.DateTimeField(auto_now_add=True)),
                ('CRTupdated_at', models.DateTimeField(auto_now=True)),
                ('CRTslug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
