# Generated by Django 5.1.1 on 2025-04-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
