# Generated by Django 5.2.1 on 2025-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_pictures/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(default='fa-mobile-alt', max_length=50, verbose_name='Logo (FontAwesome class)'),
        ),
    ]
