# Generated by Django 5.2.1 on 2025-06-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_brand_image_alter_brand_logo'),
        ('product', '0004_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#000', 'Black'), ('#fff', 'White'), ('#f00', 'Red'), ('#0f0', 'Green'), ('#00f', 'Blue'), ('#ff0', 'Yellow'), ('#ffa500', 'Orange'), ('#ffc0cb', 'Pink'), ('#800080', 'Purple'), ('#a52a2a', 'Brown'), ('#808080', 'Gray'), ('#c0c0c0', 'Silver'), ('#ffd700', 'Gold'), ('#f5f5dc', 'Beige'), ('#00ffff', 'Cyan'), ('#ff00ff', 'Magenta'), ('#00ff00', 'Lime'), ('#000080', 'Navy'), ('#008080', 'Teal'), ('#800000', 'Maroon'), ('#808000', 'Olive'), ('#4b0082', 'Indigo'), ('#ee82ee', 'Violet'), ('#40e0d0', 'Turquoise'), ('#ff7f50', 'Coral'), ('#fa8072', 'Salmon'), ('#98ff98', 'Mint'), ('#e6e6fa', 'Lavender')], max_length=20)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
        ),
    ]
