# Generated by Django 5.2.1 on 2025-06-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
    ]
