# Generated by Django 5.1.1 on 2025-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation_code',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
    ]
